LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgHelp( HWND, UINT, WPARAM, LPARAM );
BOOL CALLBACK DlgResize( HWND, UINT, WPARAM, LPARAM );
void AddMenus(HWND);
void AddColors(HWND);
void AddShapes(HWND);
void AddSpecificShapes(HWND);
void loadImages();
void DrawSelectedColors(HWND);
void CreateStatic(HWND);
void CreateTrackBars(HWND);
void GetTrackBarsPosition();
void SetCanvas(HWND);
void SetPaint(HWND);
void DrawDiamond(HDC,  LPARAM);
void DrawHexagon(HDC,  LPARAM);
void DestroyShapes();
void AddTools(HWND);
void SaveCanvasChanges(HWND hwnd);
void DrawCanvas(HWND hwnd);
void DrawOpenFile(HWND hwnd);
void ShowCursorPosition(HWND, LPARAM);
void CreateResizeControls(HWND);
void UpdateResize();
void CreateCheckBoxes(HWND);
void SaveBitmapToFile(HBITMAP, LPCTSTR);
void PrintCurrentCanvas(HWND);
void savebitmap();
